server: 
  port: 8088
  context-path: /fisco-bcos-browser

spring: 
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/testDB?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  
mybatis:  
  mapper-locations: classpath:mapper/*.xml  

constant: 
  cronBlockChainInfo: 0/10 * * * * ?
  cronBlockInfo: 0/10 * * * * ?
  cronTxnByDay: 30 0/1 * * * ?
  cronAyncNode: 0 0/10 * * * ?
  cronIfNodeActive: 0 0/1 * * * ?
  handleBlocks: 50
  
logging: 
  config: classpath:log4j2.xml